/**
 * Mock Data for Development
 * Use these credentials to test the app without a backend
 */

export const MOCK_USERS = [
  {
    id: '1',
    email: 'demo@example.com',
    password: 'demo123456',
    name: 'John Developer',
    role: 'job_seeker',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    title: 'Full Stack Engineer',
    company: 'Tech Corp',
    bio: 'Passionate about building scalable applications',
    location: 'San Francisco, CA',
  },
  {
    id: '2',
    email: 'recruiter@example.com',
    password: 'recruiter123',
    name: 'Sarah Recruiter',
    role: 'recruiter',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    title: 'Senior Recruiter',
    company: 'Tech Talents Inc',
    bio: 'Connecting great talent with amazing opportunities',
    location: 'New York, NY',
  },
  {
    id: '3',
    email: 'hiring@example.com',
    password: 'hiring123456',
    name: 'Mike Manager',
    role: 'hiring_manager',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
    title: 'Engineering Manager',
    company: 'Innovation Labs',
    bio: 'Building high-performing engineering teams',
    location: 'Austin, TX',
  },
];

export const MOCK_POSTS = [
  {
    id: '1',
    author_id: '1',
    content: 'Just launched my new portfolio website! Check it out and let me know what you think.',
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    likes: 45,
    comments: 12,
    shares: 5,
  },
  {
    id: '2',
    author_id: '2',
    content: 'We are hiring! Looking for talented React developers to join our team. DM for details.',
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    likes: 120,
    comments: 28,
    shares: 15,
  },
  {
    id: '3',
    author_id: '3',
    content: 'Tips for acing your technical interview: 1) Practice algorithms, 2) Explain your thinking, 3) Ask clarifying questions',
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    likes: 200,
    comments: 45,
    shares: 32,
  },
];

export const MOCK_JOBS = [
  {
    id: '1',
    title: 'Product Support Operations, Team Lead',
    company: 'Stripe',
    location: 'Bengaluru',
    salary_min: 150000,
    salary_max: 200000,
    description: 'We are looking for an experienced full stack engineer to join our growing team.',
    requirements: ['5+ years experience', 'React/Node.js', 'PostgreSQL', 'AWS'],
    posted_at: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    title: 'Payments Analyst',
    company: 'Stripe',
    location: 'Bengaluru, India',
    salary_min: 120000,
    salary_max: 160000,
    description: 'Design beautiful and intuitive user experiences for our platform.',
    requirements: ['3+ years design experience', 'Figma', 'UX Research', 'Prototyping'],
    posted_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    title: 'Product Manager, Payments Intelligence',
    company: 'Stripe',
    location: 'US',
    salary_min: 140000,
    salary_max: 180000,
    description: 'Build and maintain our cloud infrastructure with a focus on reliability.',
    requirements: ['4+ years DevOps experience', 'Kubernetes', 'Docker', 'Terraform'],
    posted_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    title: 'Senior Software Engineer',
    company: 'Google',
    location: 'Mountain View, CA',
    salary_min: 180000,
    salary_max: 250000,
    description: 'Join our team building next-generation cloud services.',
    requirements: ['7+ years experience', 'Java/Python', 'Distributed Systems', 'GCP'],
    posted_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    title: 'UX Researcher',
    company: 'Meta',
    location: 'Menlo Park, CA',
    salary_min: 130000,
    salary_max: 170000,
    description: 'Conduct user research to inform product decisions.',
    requirements: ['4+ years UX research', 'Quantitative & Qualitative methods', 'Data analysis'],
    posted_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '6',
    title: 'Machine Learning Engineer',
    company: 'OpenAI',
    location: 'San Francisco, CA',
    salary_min: 200000,
    salary_max: 300000,
    description: 'Build cutting-edge AI models and infrastructure.',
    requirements: ['5+ years ML experience', 'PyTorch/TensorFlow', 'NLP', 'Large-scale systems'],
    posted_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '7',
    title: 'Frontend Engineer',
    company: 'Vercel',
    location: 'Remote',
    salary_min: 140000,
    salary_max: 190000,
    description: 'Build the future of web development with Next.js.',
    requirements: ['4+ years frontend', 'React/Next.js', 'TypeScript', 'Performance optimization'],
    posted_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '8',
    title: 'Data Scientist',
    company: 'Netflix',
    location: 'Los Gatos, CA',
    salary_min: 160000,
    salary_max: 220000,
    description: 'Analyze user behavior and optimize recommendation systems.',
    requirements: ['5+ years data science', 'Python/R', 'Machine Learning', 'SQL'],
    posted_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '9',
    title: 'Security Engineer',
    company: 'Apple',
    location: 'Cupertino, CA',
    salary_min: 170000,
    salary_max: 230000,
    description: 'Protect our users and infrastructure from security threats.',
    requirements: ['6+ years security', 'Penetration testing', 'Cryptography', 'Incident response'],
    posted_at: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_MESSAGES = [
  {
    id: '1',
    sender_id: '2',
    receiver_id: '1',
    content: 'Hi John! Your profile caught my attention. Are you interested in a Senior Engineer role?',
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    read: true,
  },
  {
    id: '2',
    sender_id: '1',
    receiver_id: '2',
    content: 'Hi Sarah! Thanks for reaching out. I would love to learn more about the opportunity.',
    created_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    read: true,
  },
  {
    id: '3',
    sender_id: '2',
    receiver_id: '1',
    content: 'Great! The role involves leading a team of 5 engineers. Interested in a call?',
    created_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    read: false,
  },
];

export const MOCK_CONVERSATIONS = [
  {
    id: '1',
    user_id: '2',
    name: 'Sarah Recruiter',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    last_message: 'Great! The role involves leading a team of 5 engineers. Interested in a call?',
    last_message_time: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    unread_count: 1,
  },
  {
    id: '2',
    user_id: '3',
    name: 'Mike Manager',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
    last_message: 'Thanks for applying! We will review and get back to you soon.',
    last_message_time: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    unread_count: 0,
  },
];

export const MOCK_COMPANIES = [
  {
    id: '1',
    name: 'Tech Talents Inc',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=TT',
    description: 'Leading recruitment platform for tech professionals',
    industry: 'HR Tech',
    size: '50-200',
    location: 'San Francisco, CA',
    website: 'https://techtalents.com',
  },
  {
    id: '2',
    name: 'Innovation Labs',
    logo: 'https://api.dicebear.com/7.x/initials/svg?seed=IL',
    description: 'Building next-generation software solutions',
    industry: 'Software Development',
    size: '200-500',
    location: 'Austin, TX',
    website: 'https://innovationlabs.com',
  },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: '1',
    type: 'message',
    title: 'New Message from Sarah',
    description: 'Are you interested in a Senior Engineer role?',
    read: false,
    created_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    type: 'application',
    title: 'Application Update',
    description: 'Your application has been moved to the next round',
    read: true,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    type: 'job',
    title: 'New Job Recommendation',
    description: 'Senior Full Stack Engineer at Tech Corp',
    read: true,
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
];
